/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package hospedajepro;
import hospedajepro.ConexionBD;
// Importación de clases necesarias para trabajar con bases de datos en Java
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jesus
 */
public class HabitacionDisponible extends javax.swing.JInternalFrame {

    /**
     * Creates new form HabitacionDisponible
     */
    public HabitacionDisponible() {
        initComponents();
        ListarDatos(); // Llamada para cargar los datos en la tabla
    }
    
     private void ListarDatos() {
        
          ConexionBD conexion = new ConexionBD();
        
        try{
            
            String consulta = "SELECT * FROM HABITACION";
            Connection con = conexion.conectar();
            Statement cn = con.createStatement();
            ResultSet res = cn.executeQuery(consulta);
            
            DefaultTableModel modelo = new DefaultTableModel();
            
            ResultSetMetaData metaData = res.getMetaData();
            int numeroColumnas = metaData.getColumnCount();
            for( int i = 1; i <= numeroColumnas; i++ ) {
                modelo.addColumn(metaData.getColumnName(i));
            }
            
            while(res.next()) {
                Object[] fila = new Object[numeroColumnas];
                for( int i = 1; i <= numeroColumnas; i++ ) {
                        fila[(i - 1)] = res.getObject(i);
                }
                modelo.addRow(fila);
            }

            tableHabitacion.setModel(modelo);
            
        } catch(Exception e){
            System.out.println(e.toString());
        }
     
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ListarDatos = new javax.swing.JScrollPane();
        tableHabitacion = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Habitaciones"));

        ListarDatos.setName("spanelCliente"); // NOI18N

        tableHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IDCLIENTE", "NOMBRE", "Title 3", "Title 4"
            }
        ));
        ListarDatos.setViewportView(tableHabitacion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1021, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ListarDatos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTable tableHabitacion;
    // End of variables declaration//GEN-END:variables
}
