CREATE TABLE CLIENTE(
    idcliente   NUMBER(9) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre      VARCHAR(50) NOT NULL,
    apellido    VARCHAR(50) NOT NULL,
    dni         CHAR(8)     NOT NULL,
    telefono    VARCHAR(15) NOT NULL,
    direccion   VARCHAR(70) NOT NULL,
    
    CONSTRAINT pk_idcliente PRIMARY KEY (idcliente)
);

SELECT * FROM CLIENTE;

CREATE TABLE HABITACION(
    idhabitacion        NUMBER(9) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre              VARCHAR(60)     NOT NULL,
    numero              CHAR(2)         NOT NULL,
    precio              NUMBER(8,2)     NOT NULL,
    piso                CHAR(2)         NOT NULL,
    descripcion         VARCHAR(80)     NOT NULL,   
    estado              VARCHAR2(10)    DEFAULT 'Disponible' CHECK (estado IN ('Disponible', 'Ocupada','Mantenimiento')),
    
    CONSTRAINT pk_idhabitacion PRIMARY KEY (idhabitacion)
);

select * from HABITACION;

INSERT INTO HABITACION (NOMBRE, NUMERO, PRECIO, PISO, DESCRIPCION, ESTADO)
VALUES ('Individual', '10', 150.50, '1', 'Habitación sencilla', 'Disponible');

CREATE TABLE RESERVAS(
    idreserva       NUMBER(9) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fechaentrada    DATE        NOT NULL,
    fechasalida     DATE        NOT NULL,
    cant_personas   NUMBER(3)   NOT NULL,        
    idcliente       NUMBER(9)   NOT NULL,
    idhabitacion    NUMBER(9)   NOT NULL,
    estado          VARCHAR2(10) DEFAULT 'Confirmada' CHECK (estado IN ('Confirmada', 'Cancelada')),
    
    CONSTRAINT pk_idreserva PRIMARY KEY (idreserva),
    CONSTRAINT fk_idcliente_cl FOREIGN KEY (idcliente) REFERENCES CLIENTE (idcliente),
    CONSTRAINT fk_idhabitacion_hb FOREIGN KEY (idhabitacion) REFERENCES HABITACION (idhabitacion)
);

CREATE TABLE PAGO(
    idpago          NUMBER(9) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    monto           NUMBER(8,2)     NOT NULL,
    comprobante     VARCHAR2(10)    CHECK (comprobante IN ('Factura', 'Boleta')) NOT NULL,
    idreserva       NUMBER(9)       NOT NULL,
    fecha           DATE            NOT NULL,
    
    CONSTRAINT pk_idpago PRIMARY KEY (idpago),
    CONSTRAINT fk_idreserva_rc FOREIGN KEY (idreserva) REFERENCES RESERVAS (idreserva)
);



